Refactor presentation verification
energywebfoundation/ssi pull request #46
Opened 2022-04-01 17:04 UTC by jrhender

Refactor of the presentation submission verification code of vc-api. In particular, take a look `VpRequestSubmissionVerifier` as this is the core class of the refactor.

2022-04-01 17:05 UTC, jrhender commented on apps/nestjs-wallet/src/vc-api/vp-request-submission-verifier.ts
> + *  - Authority of Issuer: TODO TODO TODO
@nichonien I'm hoping to use the role governance verification code that you are writing to do this bit

2022-04-02 12:44 UTC, Harasz approved these changes

2022-04-05 08:09 UTC, JGiter requested changes

2022-04-05 10:32 UTC, JGiter commented on apps/nestjs-wallet/src/vc-api/exchanges/entities/transaction.entity.ts
> +    verifier: VpRequestSubmissionVerifier
Nevermind. I realized that it is conforms with vc-api spec

2022-04-25 06:13 UTC, jrhender commented
Closing as will be implemented instead here: https://github.com/energywebfoundation/ssi/pull/55

2022-04-25 06:13 UTC, closed without merging