docs: add context explainer
energywebfoundation/ssi pull request #67
Opened 2022-05-16 16:54 UTC by jrhender

2022-05-16 16:59 UTC, whitneypurdum commented on apps/vc-api/README.md
> +The Verifiable Credentials specification used context to ensure that the meanings of terms in a credential are shared by all parties.
'uses' or 'used'?

2022-05-16 17:21 UTC, Harasz requested changes

2022-05-16 17:21 UTC, Harasz commented on apps/vc-api/docs/contexts.md
> +See the [Contexts section](w3.org/TR/vc-data-model/#contexts) of the specification for more generation information about context in VCs.
```suggestion
See the [Contexts section](https://www.w3.org/TR/vc-data-model/#contexts) of the specification for more generation information about context in VCs.
```

2022-05-16 17:21 UTC, Harasz commented on apps/vc-api/docs/contexts.md
> +For more information on this, see the (DIDKit documentation on document loading[https://spruceid.dev/docs/didkit/document-loading/].
```suggestion
For more information on this, see the [DIDKit documentation on document loading](https://spruceid.dev/docs/didkit/document-loading/).
```

2022-05-16 17:21 UTC, Harasz commented on apps/vc-api/docs/contexts.md
> +For example, a veriable credential may contain a `@context` array as follows:
```suggestion
For example, a verifiable credential may contain a `@context` array as follows:
```

2022-05-16 17:21 UTC, Harasz commented on apps/vc-api/docs/contexts.md
> +}
```suggestion
   "@context": [
      "https://www.w3.org/2018/credentials/v1",
      {
         "custom": "https://example.com/custom-context-2022#",
         "customObject": {
            "@id": "custom:customObject",
            "@type": "custom:ExampleObject"
         },
         "customField": "custom:customField"
      }
   ],
   "id": "urn:uuid:7f94d397-3e70-4a43-945e-1a13069e636f",
   "type": [
      "VerifiableCredential"
   ],
   "credentialSubject":{
      "id": "did:example:123",
      "customObject": {
        "customField": "customValue"
      }
   },
   "issuer": "did:example:456",
   "issuanceDate": "2022-03-18T08:57:32.477Z"
}
```

2022-05-17 06:57 UTC, JGiter approved these changes

2022-05-17 06:57 UTC, JGiter commented on apps/vc-api/docs/contexts.md
> +See the [Contexts section](w3.org/TR/vc-data-model/#contexts) of the specification for more generation information about context in VCs.
general?

2022-05-17 06:57 UTC, JGiter commented on apps/vc-api/docs/contexts.md
> +to issue or verify a credential which refers a context which has is not in the DIDKit [default contexts](https://github.com/spruceid/ssi/tree/main/contexts).
```suggestion
to issue or verify a credential which refers a context which is not in the DIDKit [default contexts](https://github.com/spruceid/ssi/tree/main/contexts).
```

2022-05-17 15:34 UTC, merged